import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { db } from "@/lib/db";
import { SiteHeader } from "@/components/header";
import { Movie } from "@/movie-data";
import { cache } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const Data = cache(async () => {
    const item: Movie[] = await db.movie.findMany();
    return item;
  });

  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-950 font-sans antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <SiteHeader />
          <div className="relative flex flex-col min-h-screen">
            <div className="flex items-center space-x-6"></div>
            <div className="flex-1">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
